#!/usr/bin/env sh

set -eu

REPO_ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
VERSION_ENV_FILE="${VERSION_ENV_FILE:-$REPO_ROOT/version.env}"

APP_NAME="${APP_NAME:-CodexAgentBar}"
BUNDLE_ID="${BUNDLE_ID:-com.lonewolfyx.CodexAgentBar}"
CONFIGURATION="${CONFIGURATION:-release}"
DMG_VOLUME_NAME="${DMG_VOLUME_NAME:-$APP_NAME}"
SIGN_APP="${SIGN_APP:-1}"
CODE_SIGN_IDENTITY="${CODE_SIGN_IDENTITY:--}"

ENV_VERSION_WAS_SET=0
ENV_BUILD_NUMBER_WAS_SET=0
if [ "${VERSION+x}" = x ]; then
    ENV_VERSION="$VERSION"
    ENV_VERSION_WAS_SET=1
fi
if [ "${BUILD_NUMBER+x}" = x ]; then
    ENV_BUILD_NUMBER="$BUILD_NUMBER"
    ENV_BUILD_NUMBER_WAS_SET=1
fi

VERSION="1.0.0"
BUILD_NUMBER="1"
if [ -f "$VERSION_ENV_FILE" ]; then
    . "$VERSION_ENV_FILE"
fi
if [ "$ENV_VERSION_WAS_SET" -eq 1 ]; then
    VERSION="$ENV_VERSION"
fi
if [ "$ENV_BUILD_NUMBER_WAS_SET" -eq 1 ]; then
    BUILD_NUMBER="$ENV_BUILD_NUMBER"
fi

BUILD_DIR="$REPO_ROOT/.build/$CONFIGURATION"
DIST_DIR="${DIST_DIR:-$REPO_ROOT/dist}"
DMG_PATH="$DIST_DIR/$APP_NAME-$VERSION.dmg"
ASSETS_DIR="$REPO_ROOT/Assets"
ICON_SOURCE="$ASSETS_DIR/app-icon.png"
MENU_BAR_ICON_SOURCE="$ASSETS_DIR/app-icon-light.png"
ARROW_ICON_SOURCE="$ASSETS_DIR/right.png"
OUTPUT_WAS_SET=0

usage() {
    DEFAULT_DMG_PATH="$DMG_PATH"
    if [ "$OUTPUT_WAS_SET" -eq 0 ]; then
        DEFAULT_DMG_PATH="$DIST_DIR/$APP_NAME-$VERSION.dmg"
    fi

    cat <<EOF
Usage: $(basename "$0") [options]

Builds a macOS .app bundle from the Swift package and packages it as a DMG.

Options:
  -n, --name NAME          App name. Default: $APP_NAME
  -b, --bundle-id ID      Bundle identifier. Default: $BUNDLE_ID
  -v, --version VERSION   App version and DMG suffix. Default: $VERSION
  -o, --output PATH       DMG output path. Default: $DEFAULT_DMG_PATH
  -h, --help              Show this help.

Environment overrides:
  APP_NAME, BUNDLE_ID, VERSION, BUILD_NUMBER, CONFIGURATION, DIST_DIR,
  DMG_VOLUME_NAME, VERSION_ENV_FILE, SIGN_APP, CODE_SIGN_IDENTITY

Version file:
  $VERSION_ENV_FILE
EOF
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        -n|--name)
            if [ "$#" -lt 2 ]; then
                echo "Missing value for $1" >&2
                exit 1
            fi
            APP_NAME="$2"
            shift 2
            ;;
        -b|--bundle-id)
            if [ "$#" -lt 2 ]; then
                echo "Missing value for $1" >&2
                exit 1
            fi
            BUNDLE_ID="$2"
            shift 2
            ;;
        -v|--version)
            if [ "$#" -lt 2 ]; then
                echo "Missing value for $1" >&2
                exit 1
            fi
            VERSION="$2"
            shift 2
            ;;
        -o|--output)
            if [ "$#" -lt 2 ]; then
                echo "Missing value for $1" >&2
                exit 1
            fi
            DMG_PATH="$2"
            OUTPUT_WAS_SET=1
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

EXECUTABLE="$BUILD_DIR/$APP_NAME"
DMG_ARROW_NAME="      "
DMG_TITLE_NAME="             "
if [ "$OUTPUT_WAS_SET" -eq 0 ]; then
    DMG_PATH="$DIST_DIR/$APP_NAME-$VERSION.dmg"
fi

WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/codex-agent-bar-dmg.XXXXXX")"
APP_BUNDLE="$WORK_DIR/$APP_NAME.app"
STAGING_DIR="$WORK_DIR/dmg-staging"
TEMP_DMG="$WORK_DIR/$APP_NAME-temp.dmg"
ICONSET_DIR="$WORK_DIR/AppIcon.iconset"
APP_ICON="$WORK_DIR/AppIcon.icns"
ARROW_ICON_WORK="$WORK_DIR/DmgArrowIcon.png"
ARROW_RSRC="$WORK_DIR/DmgArrowIcon.rsrc"
DMG_ARROW_PATH="$STAGING_DIR/$DMG_ARROW_NAME"
TITLE_ICON_WORK="$WORK_DIR/DmgTitleIcon.png"
TITLE_ICON_SWIFT="$WORK_DIR/DmgTitleIcon.swift"
TITLE_RSRC="$WORK_DIR/DmgTitleIcon.rsrc"
DMG_TITLE_PATH="$STAGING_DIR/$DMG_TITLE_NAME"

cleanup_build() {
    rm -rf "$WORK_DIR"
}
trap cleanup_build EXIT HUP INT TERM

require_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "Missing required command: $1" >&2
        exit 1
    fi
}

require_command swift
require_command hdiutil
require_command sips
require_command iconutil
require_command base64
require_command Rez
require_command DeRez
require_command SetFile
require_command codesign

create_title_icon() {
    cat > "$TITLE_ICON_SWIFT" <<'SWIFT'
import AppKit

let output = CommandLine.arguments[1]
let title = CommandLine.arguments[2]
let size = NSSize(width: 1024, height: 256)
let image = NSImage(size: size)

image.lockFocus()
NSColor.clear.setFill()
NSRect(origin: .zero, size: size).fill()

let paragraph = NSMutableParagraphStyle()
paragraph.alignment = .center
let fontSize: CGFloat = 66
let titleFont =
    NSFont(name: "JetBrainsMono-Regular", size: fontSize)
    ?? NSFont(name: "JetBrains Mono", size: fontSize)
    ?? NSFont.monospacedSystemFont(ofSize: fontSize, weight: .regular)
let attrs: [NSAttributedString.Key: Any] = [
    .font: titleFont,
    .foregroundColor: NSColor.black,
    .paragraphStyle: paragraph,
    .kern: 1.0,
]
title.draw(in: NSRect(x: 0, y: 78, width: size.width, height: 104), withAttributes: attrs)
image.unlockFocus()

guard let tiff = image.tiffRepresentation,
      let bitmap = NSBitmapImageRep(data: tiff),
      let png = bitmap.representation(using: .png, properties: [:]) else {
    fatalError("Could not render title image")
}

try png.write(to: URL(fileURLWithPath: output))
SWIFT

    swift "$TITLE_ICON_SWIFT" "$TITLE_ICON_WORK" "$APP_NAME"
}

sign_app_bundle() {
    if [ "$SIGN_APP" = "0" ]; then
        echo "Skipping app bundle signing because SIGN_APP=0."
        return
    fi

    if [ "$CODE_SIGN_IDENTITY" = "-" ]; then
        echo "Signing app bundle with ad-hoc identity..."
    else
        echo "Signing app bundle with identity: $CODE_SIGN_IDENTITY"
    fi

    codesign --force --sign "$CODE_SIGN_IDENTITY" "$APP_BUNDLE"
    codesign --verify --deep --strict --verbose=2 "$APP_BUNDLE"
}

write_dmg_layout() {
    base64 -D > "$STAGING_DIR/.DS_Store" <<'EOF'
AAAAAUJ1ZDEAABAAAAAIAAAAEAAAAAQKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAgAAAABAAAQAAAgACBJbG9jYmxvYgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAYAIAAgACAAIAAgACBJbG9jYmxvYgAAABAAAAFjAAABHf///////wAAAAAADQAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgSWxvY2Jsb2IAAAAQAAABYwAAAGn///////8AAAAAAAEALmJ3c3BibG9iAAAAuGJwbGlzdDAw1gECAwQFBgcHCQcLB11TaG93U3RhdHVzQmFyW1Nob3dUb29sYmFyW1Nob3dUYWJWaWV3XxAUQ29udGFpbmVyU2hvd1NpZGViYXJcV2luZG93Qm91bmRzW1Nob3dTaWRlYmFyCAgJCF8QGHt7MTYwLCA1NTl9LCB7NzEwLCA0OTB9fQgIFSMvO1Jfa2xtbm+KAAAAAAAAAQEAAAAAAAAADQAAAAAAAAAAAAAAAAAAAIsAAAABAC5pY3ZwYmxvYgAAAbBicGxpc3QwMN8QDwECAwQFBgcICQoLDA0ODxAREhATEBQUFRYXGBkaGV8QE2JhY2tncm91bmRDb2xvckJsdWVbZ3JpZFNwYWNpbmdYdGV4dFNpemVfEBJiYWNrZ3JvdW5kQ29sb3JSZWReYmFja2dyb3VuZFR5cGVfEBRiYWNrZ3JvdW5kQ29sb3JHcmVlbltncmlkT2Zmc2V0WFtncmlkT2Zmc2V0WVpheFRleHRTaXplXHNob3dJdGVtSW5mb18QEnZpZXdPcHRpb25zVmVyc2lvbllhcnJhbmdlQnldbGFiZWxPbkJvdHRvbVhpY29uU2l6ZV8QD3Nob3dJY29uUHJldmlldyM/8AAAAAAAACNAWQAAAAAAACNAMAAAAAAAABAAIwAAAAAAAAAAI0AoAAAAAAAACBQAAAAAAAAAAAAAAAAAAAABVG5vbmUJI0BgAAAAAAAACQAIACkAPwBLAFQAaQB4AI8AmwCnALIAvwDUAN4A7AD1AQcBEAEZASIBJAEtATYBNwFIAU0BTgFXAAAAAAAAAgEAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAVgAAAABAC52U3JubG9uZwAAAAEAAAAKAC4AZgBzAGUAdgBlAG4AdABzAGRJbG9jYmxvYgAAABAAAAGuAAAAJf///////wAAAAAADABBAHAAcABsAGkAYwBhAHQAaQBvAG4Ac0lsb2NibG9iAAAAEAAAAggAAAEd////////AAAAAAARAEMAbwBkAGUAeABBAGcAZQBuAHQAQgBhAHIALgBhAHAAcElsb2NibG9iAAAAEAAAAL4AAAEd////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAgLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAACAAAAABAAAAQAAAAAEAAACAAAAAAQAAAQAAAAABAAACAAAAAAEAAAQAAAAAAAAAAAEAABAAAAAAAQAAIAAAAAABAABAAAAAAAEAAIAAAAAAAQABAAAAAAABAAIAAAAAAAEABAAAAAAAAQAIAAAAAAABABAAAAAAAAEAIAAAAAAAAQBAAAAAAAABAIAAAAAAAAEBAAAAAAAAAQIAAAAAAAABBAAAAAAAAAEIAAAAAAAAARAAAAAAAAABIAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAEAsAAABFAAAECgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBERTREIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAIAAAAGAAAAAAAAAAAQAAAIAAAAABAAABAAAAAAEAAAIAAAAAAAAAAAIAAAgAAAAYAAAAAAAAAAABAAAgAAAAAAEAAEAAAAAAAQAAgAAAAAABAAEAAAAAAAEAAgAAAAAAAQAEAAAAAAABAAgAAAAAAAEAEAAAAAAAAQAgAAAAAAABAEAAAAAAAAEAgAAAAAAAAQEAAAAAAAABAgAAAAAAAAEEAAAAAAAAAQgAAAAAAAABEAAAAAAAAAEgAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==

EOF
}

if [ ! -f "$ICON_SOURCE" ]; then
    echo "Expected app icon not found: $ICON_SOURCE" >&2
    exit 1
fi

if [ ! -f "$MENU_BAR_ICON_SOURCE" ]; then
    echo "Expected menu bar icon not found: $MENU_BAR_ICON_SOURCE" >&2
    exit 1
fi

if [ ! -f "$ARROW_ICON_SOURCE" ]; then
    echo "Expected DMG arrow icon not found: $ARROW_ICON_SOURCE" >&2
    exit 1
fi

echo "Building $APP_NAME ($CONFIGURATION)..."
cd "$REPO_ROOT"
swift build -c "$CONFIGURATION"

if [ ! -x "$EXECUTABLE" ]; then
    echo "Expected executable not found: $EXECUTABLE" >&2
    exit 1
fi

echo "Creating app bundle..."
rm -rf "$DMG_PATH"
mkdir -p \
    "$APP_BUNDLE/Contents/MacOS" \
    "$APP_BUNDLE/Contents/Resources" \
    "$STAGING_DIR" \
    "$(dirname -- "$DMG_PATH")"
cp "$EXECUTABLE" "$APP_BUNDLE/Contents/MacOS/$APP_NAME"

echo "Preparing app icon..."
mkdir -p "$ICONSET_DIR"
sips -z 16 16 "$ICON_SOURCE" --out "$ICONSET_DIR/icon_16x16.png" >/dev/null
sips -z 32 32 "$ICON_SOURCE" --out "$ICONSET_DIR/icon_16x16@2x.png" >/dev/null
sips -z 32 32 "$ICON_SOURCE" --out "$ICONSET_DIR/icon_32x32.png" >/dev/null
sips -z 64 64 "$ICON_SOURCE" --out "$ICONSET_DIR/icon_32x32@2x.png" >/dev/null
sips -z 128 128 "$ICON_SOURCE" --out "$ICONSET_DIR/icon_128x128.png" >/dev/null
sips -z 256 256 "$ICON_SOURCE" --out "$ICONSET_DIR/icon_128x128@2x.png" >/dev/null
sips -z 256 256 "$ICON_SOURCE" --out "$ICONSET_DIR/icon_256x256.png" >/dev/null
sips -z 512 512 "$ICON_SOURCE" --out "$ICONSET_DIR/icon_256x256@2x.png" >/dev/null
sips -z 512 512 "$ICON_SOURCE" --out "$ICONSET_DIR/icon_512x512.png" >/dev/null
sips -z 1024 1024 "$ICON_SOURCE" --out "$ICONSET_DIR/icon_512x512@2x.png" >/dev/null
iconutil -c icns "$ICONSET_DIR" -o "$APP_ICON"
cp "$APP_ICON" "$APP_BUNDLE/Contents/Resources/AppIcon.icns"
cp "$ICON_SOURCE" "$APP_BUNDLE/Contents/Resources/AppIcon.png"
cp "$MENU_BAR_ICON_SOURCE" "$APP_BUNDLE/Contents/Resources/MenuBarIcon.png"
if [ -f "$VERSION_ENV_FILE" ]; then
    cp "$VERSION_ENV_FILE" "$APP_BUNDLE/Contents/Resources/version.env"
fi

cat > "$APP_BUNDLE/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleExecutable</key>
    <string>$APP_NAME</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundleIdentifier</key>
    <string>$BUNDLE_ID</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>$VERSION</string>
    <key>CFBundleVersion</key>
    <string>$BUILD_NUMBER</string>
    <key>LSMinimumSystemVersion</key>
    <string>13.0</string>
    <key>LSUIElement</key>
    <true/>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
EOF

sign_app_bundle

echo "Preparing DMG staging directory..."
cp -R "$APP_BUNDLE" "$STAGING_DIR/"
ln -s /Applications "$STAGING_DIR/Applications"
touch "$DMG_ARROW_PATH"
touch "$DMG_TITLE_PATH"
cp "$ARROW_ICON_SOURCE" "$ARROW_ICON_WORK"
sips -i "$ARROW_ICON_WORK" >/dev/null
DeRez -only icns "$ARROW_ICON_WORK" > "$ARROW_RSRC"
Rez -append "$ARROW_RSRC" -o "$DMG_ARROW_PATH"
SetFile -a C "$DMG_ARROW_PATH"
create_title_icon
sips -i "$TITLE_ICON_WORK" >/dev/null
DeRez -only icns "$TITLE_ICON_WORK" > "$TITLE_RSRC"
Rez -append "$TITLE_RSRC" -o "$DMG_TITLE_PATH"
SetFile -a C "$DMG_TITLE_PATH"
write_dmg_layout
rm -rf "$STAGING_DIR/.fseventsd" "$STAGING_DIR/.Spotlight-V100" "$STAGING_DIR/.Trashes"

SIZE_MB="$(du -sm "$STAGING_DIR" | awk '{ print $1 + 64 }')"

echo "Creating temporary DMG..."
hdiutil create \
    -volname "$DMG_VOLUME_NAME" \
    -srcfolder "$STAGING_DIR" \
    -ov \
    -format UDRW \
    -fs HFS+ \
    -size "${SIZE_MB}m" \
    "$TEMP_DMG" >/dev/null

echo "Compressing DMG..."
hdiutil convert "$TEMP_DMG" \
    -format UDZO \
    -imagekey zlib-level=9 \
    -o "$DMG_PATH" >/dev/null

echo "Created: $DMG_PATH"
